"use client";
import { FormEvent, useEffect, useState } from "react";

type Offer = { id: string; name: string; s2sPostbackUrl: string | null; visits: number; conversions: number; errors: number; registrations: number; ftd: number };
const field = "mt-2 block w-full border border-[#c8c3b8] bg-white px-3 py-2.5 text-sm outline-none focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#a34f2d]";
export default function OffersClient() {
  const [offers, setOffers] = useState<Offer[]>([]); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [open, setOpen] = useState(false);
  async function load() { try { const response = await fetch("/api/admin/offers"); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Offers could not be loaded."); setOffers(body.offers ?? []); } catch (e) { setError(e instanceof Error ? e.message : "Offers could not be loaded."); } }
  useEffect(() => {
    let cancelled = false;
    fetch("/api/admin/offers").then(async (response) => {
      const body = await response.json();
      if (!response.ok) throw new Error(body.error?.message ?? "Offers could not be loaded.");
      if (!cancelled) setOffers(body.offers ?? []);
    }).catch((e: unknown) => { if (!cancelled) setError(e instanceof Error ? e.message : "Offers could not be loaded."); });
    return () => { cancelled = true; };
  }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(null); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/admin/offers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: form.get("name"), s2sPostbackUrl: form.get("s2sPostbackUrl") }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to create offer."); event.currentTarget.reset(); setOpen(false); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create offer."); } finally { setSaving(false); } }
  return <>
    <div className="mt-6 flex justify-end"><button type="button" onClick={() => setOpen(true)} className="bg-[#17202a] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#a34f2d] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#a34f2d]">New offer +</button></div>
    {error ? <div role="alert" className="mt-8 border border-[#a34f2d] bg-[#fffaf5] px-4 py-3 text-sm text-[#8b3c22]">{error}</div> : null}
    {open ? <section id="new-offer" className="mt-8 border border-[#c8c3b8] bg-[#faf8f3] p-5 sm:p-7" aria-labelledby="new-offer-title"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#a34f2d]">Offer setup</p><h2 id="new-offer-title" className="mt-2 text-2xl font-semibold">Create offer</h2></div><button type="button" onClick={() => setOpen(false)} className="text-sm font-semibold text-[#59636c] underline underline-offset-4 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#a34f2d]">Close</button></div><form onSubmit={submit} className="mt-6 grid gap-5 sm:grid-cols-2"><label className="text-xs font-semibold uppercase tracking-[0.12em] text-[#59636c]">Name<input required name="name" maxLength={200} className={field} placeholder="Registration offer" /></label><label className="text-xs font-semibold uppercase tracking-[0.12em] text-[#59636c]">S2S postback URL<p className="mt-1 normal-case tracking-normal text-[11px] font-normal text-[#59636c]">Optional. HTTPS only.</p><input name="s2sPostbackUrl" type="url" className={field} placeholder="https://partner.example/postback?cid={cid}" /></label><div className="sm:col-span-2"><button disabled={saving} type="submit" className="bg-[#17202a] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#a34f2d] disabled:opacity-60 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#a34f2d]">{saving ? "Creating…" : "Create offer"}</button></div></form></section> : null}
    <section className="mt-8 overflow-x-auto border border-[#c8c3b8] bg-[#faf8f3]" aria-label="Offer performance"><table className="w-full min-w-[860px] border-collapse text-left text-sm"><caption className="sr-only">Offer performance</caption><thead className="bg-[#e8e3d9] text-xs uppercase tracking-[0.1em] text-[#59636c]"><tr>{["Name", "Visits", "Conversions", "Error", "Registration", "FTD", "S2S postback"].map((heading) => <th key={heading} className="px-4 py-3 font-semibold">{heading}</th>)}</tr></thead><tbody>{offers.map((offer) => <tr key={offer.id} className="border-t border-[#ded9cf] hover:bg-[#f2eee5]"><td className="px-4 py-4 font-semibold">{offer.name}</td><td className="px-4 py-4 font-mono">{offer.visits.toLocaleString()}</td><td className="px-4 py-4 font-mono">{offer.conversions.toLocaleString()}</td><td className="px-4 py-4 font-mono">{offer.errors.toLocaleString()}</td><td className="px-4 py-4 font-mono">{offer.registrations.toLocaleString()}</td><td className="px-4 py-4 font-mono">{offer.ftd.toLocaleString()}</td><td className="max-w-xs truncate px-4 py-4 text-xs text-[#59636c]">{offer.s2sPostbackUrl ?? "Not configured"}</td></tr>)}</tbody></table>{offers.length === 0 ? <div className="border-t border-[#ded9cf] px-6 py-10"><h2 className="text-lg font-semibold">No offers yet.</h2><p className="mt-2 text-sm text-[#59636c]">Create an offer to give campaigns a reusable S2S postback destination.</p><button type="button" onClick={() => setOpen(true)} className="mt-4 bg-[#17202a] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#a34f2d]">Create first offer</button></div> : null}</section>
  </>;
}
