import Link from "next/link";

const workflow = [
  { number: "01", title: "Capture the click", text: "A campaign link creates one opaque click ID and keeps the approved ad parameters attached to it." },
  { number: "02", title: "Pass it to your site", text: "The visitor reaches your money site with the click ID ready for the conversion journey." },
  { number: "03", title: "Report the result", text: "A conversion is attributed, recorded once, and sent back to the traffic source." },
];

const plans = [
  { name: "Starter", price: "$100", note: "For a focused first setup", features: ["Click and conversion tracking", "One campaign workspace", "Essential dashboard metrics"], featured: false },
  { name: "Operator", price: "$300", note: "Best fit for daily campaign work", features: ["Everything in Starter", "Campaign, offer, and traffic-source setup", "S2S conversion postbacks", "Delivery health and retries"], featured: true },
  { name: "Expanded", price: "$500", note: "For a broader active setup", features: ["Everything in Operator", "More campaign configurations", "More traffic-source connections", "The same focused interface"], featured: false },
];

export default function Home() {
  return (
    <main className="min-h-screen overflow-hidden bg-[#F0F0F0] text-[#121212]">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-12" aria-label="Main navigation">
        <Link href="/" className="flex items-center gap-1 border-2 border-[#121212] bg-[#FFFFFF] px-2 py-1 text-lg font-black tracking-[-0.03em] shadow-[3px_3px_0_#121212]"><span aria-hidden="true" className="h-3 w-3 rounded-full bg-[#D02020]" /><span aria-hidden="true" className="h-3 w-3 bg-[#1040C0]" /><span aria-hidden="true" className="h-0 w-0 border-x-[6px] border-b-[10px] border-x-transparent border-b-[#F0C020]" /><span className="ml-1">Track.in</span></Link>
        <div className="flex items-center gap-5 text-sm font-semibold"><a href="#pricing" className="text-[#121212] hover:text-[#121212]">Pricing</a><Link href="/admin" className="border-2 border-[#121212] px-4 py-2 hover:bg-[#121212] hover:text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#D02020]">Open dashboard</Link></div>
      </nav>

      <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-16 sm:px-8 sm:pt-24 lg:grid-cols-[1.05fr_0.95fr] lg:items-center lg:px-12 lg:pb-28"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#D02020]">Conversion tracking, reduced to the work</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-[0.98] tracking-[-0.06em] sm:text-7xl">Know which clicks became conversions.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#121212]">Track.in gives your campaigns a click ID, keeps attribution through your money site, and reports the conversion back to your traffic source. No unused platform maze attached.</p><div className="mt-9 flex flex-wrap items-center gap-4"><Link href="/admin" className="bg-[#1040C0] px-5 py-3 text-sm font-semibold text-white hover:bg-[#1040C0] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#1040C0]">Open the dashboard</Link><a href="#how-it-works" className="text-sm font-semibold text-[#1040C0] underline decoration-[#121212] underline-offset-4 hover:text-[#121212]">See how it works</a></div></div><div className="relative border-2 border-[#121212] bg-[#FFFFFF] p-5 sm:p-7"><div className="flex items-center justify-between border-b-2 border-[#121212] pb-4"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#121212]">The useful path</p><span className="text-xs font-semibold text-[#D02020]">Track.in</span></div><div className="py-7"><p className="font-mono text-xs text-[#121212]">ad click</p><div className="my-3 h-px w-full bg-[#121212]" /><p className="font-mono text-xs text-[#121212]">cid = click_opaque_01</p><div className="my-3 h-px w-3/4 bg-[#121212]" /><p className="font-mono text-xs text-[#121212]">money site → conversion</p><div className="my-3 h-px w-1/2 bg-[#D02020]" /><p className="font-mono text-xs font-semibold text-[#1040C0]">postback → traffic source</p></div><p className="border-t-2 border-[#121212] pt-4 text-sm leading-6 text-[#121212]">One record for the click. One attributed conversion. One useful answer.</p></div></section>

      <section id="how-it-works" className="border-y-2 border-[#121212] bg-[#FFFFFF]"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-12 lg:py-20"><div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#D02020]">How it works</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">The parts you actually need.</h2><p className="mt-4 text-base leading-7 text-[#121212]">Your traffic source, your money site, and a private view of what happened between them. Configure the sources already in your stack, including TrafficStars, PropellerAds, and TrafficJunky.</p></div><div className="mt-12 grid gap-0 border-y-2 border-[#121212] md:grid-cols-3">{workflow.map((item) => <article key={item.number} className="border-b-2 border-[#121212] py-7 md:border-b-0 md:border-r md:px-7 md:first:pl-0 md:last:border-r-0 md:last:pr-0"><p className="font-mono text-sm text-[#D02020]">{item.number}</p><h3 className="mt-7 text-xl font-semibold">{item.title}</h3><p className="mt-3 text-sm leading-6 text-[#121212]">{item.text}</p></article>)}</div></div></section>

      <section id="pricing" className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="flex flex-col gap-5 border-b-2 border-[#121212] pb-10 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#D02020]">Pricing</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Pay for the tracking work, not a feature museum.</h2></div><p className="max-w-sm text-sm leading-6 text-[#121212]">Draft pricing for a focused product. The $300 plan is the practical center for operators who need the complete loop.</p></div><div className="mt-10 grid gap-4 lg:grid-cols-3">{plans.map((plan) => <article key={plan.name} className={`flex flex-col border-2 p-6 ${plan.featured ? "border-[#1040C0] bg-[#1040C0] text-white shadow-[0_12px_0_#121212]" : "border-[#121212] bg-[#FFFFFF]"}`}><div className="flex items-start justify-between gap-4"><h3 className="text-xl font-semibold">{plan.name}</h3>{plan.featured ? <span className="border-2 border-white/50 px-2 py-1 text-[10px] font-semibold uppercase tracking-[0.12em]">Best fit</span> : null}</div><p className={`mt-3 text-sm ${plan.featured ? "text-[#FFFFFF]" : "text-[#121212]"}`}>{plan.note}</p><p className="mt-8 text-4xl font-semibold tracking-[-0.05em]">{plan.price}<span className={`ml-1 text-sm font-normal ${plan.featured ? "text-[#FFFFFF]" : "text-[#121212]"}`}>/month</span></p><ul className={`mt-8 space-y-3 border-t-2 pt-6 text-sm leading-6 ${plan.featured ? "border-white/25 text-[#FFFFFF]" : "border-[#121212] text-[#121212]"}`}>{plan.features.map((feature) => <li key={feature} className="flex gap-3"><span aria-hidden="true" className={plan.featured ? "text-[#F0C020]" : "text-[#D02020]"}>•</span>{feature}</li>)}</ul><Link href="/admin" className={`mt-10 border-2 px-4 py-3 text-center text-sm font-semibold transition ${plan.featured ? "border-white bg-white text-[#1040C0] hover:bg-[#FFFFFF]" : "border-[#121212] text-[#121212] hover:bg-[#121212] hover:text-white"}`}>Open dashboard</Link></article>)}</div></section>

      <section className="border-t-2 border-[#121212] bg-[#121212] text-white"><div className="mx-auto flex max-w-7xl flex-col gap-7 px-5 py-14 sm:px-8 lg:flex-row lg:items-end lg:justify-between lg:px-12"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-[#F0C020]">Track.in</p><h2 className="mt-4 max-w-xl text-3xl font-semibold tracking-[-0.04em]">A smaller tracker can be the clearer one.</h2></div><Link href="/admin" className="w-fit border-2 border-white/60 px-5 py-3 text-sm font-semibold hover:bg-white hover:text-[#121212] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#F0C020]">Open private dashboard</Link></div></section>
    </main>
  );
}
