import Link from "next/link";
import type { Metadata } from "next";

import { campaignDetailFilters, getCampaignDetail } from "@/lib/admin/campaign-views";

export const metadata: Metadata = { title: "Campaign detail | Track.in", description: "Private campaign detail." };
export const dynamic = "force-dynamic";

const dateFormatter = new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" });
const dayFormatter = new Intl.DateTimeFormat("en", { month: "short", day: "numeric", timeZone: "UTC" });

function formatMinor(value: number, currency: string) { return `${value.toLocaleString()} ${currency}`; }
function shortId(value: string) { return `${value.slice(0, 8)}…${value.slice(-6)}`; }
function statusClass(status: string) { return status === "active" || status === "delivered" ? "bg-[#F0C020] text-[#121212]" : status.includes("failed") ? "bg-[#F0F0F0] text-[#D02020]" : "bg-[#E0E0E0] text-[#121212]"; }

export default async function CampaignDetailPage({ params, searchParams }: { params: Promise<{ campaignId: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const [{ campaignId }, input] = await Promise.all([params, searchParams]);
  const query = new URLSearchParams();
  for (const [key, value] of Object.entries(input)) if (typeof value === "string") query.set(key, value);
  let detail = null;
  try { detail = await getCampaignDetail(campaignId, campaignDetailFilters(query)); } catch { detail = null; }

  if (!detail) return <main className="min-h-screen bg-[#F0F0F0] px-5 py-8 text-[#121212] sm:px-8 lg:px-12 lg:py-12"><div className="mx-auto max-w-2xl border-2 border-[#D02020] bg-[#FFFFFF] px-6 py-8"><Link href="/admin/campaigns" className="text-xs font-semibold uppercase tracking-[0.16em] text-[#D02020] hover:underline">← Campaigns</Link><h1 className="mt-5 text-2xl font-semibold">Campaign detail unavailable.</h1><p className="mt-3 text-sm leading-6 text-[#121212]">This campaign may not exist, or its data could not be loaded. Try again or return to the campaign list.</p></div></main>;

  return <main className="min-h-screen bg-[#F0F0F0] text-[#121212]"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:px-12 lg:py-12">
    <header className="flex flex-col gap-5 border-b-2 border-[#121212] pb-8 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/admin/campaigns" className="text-xs font-semibold uppercase tracking-[0.18em] text-[#D02020] hover:underline">← Campaigns</Link><h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">{detail.campaign.name}</h1><p className="mt-2 font-mono text-sm text-[#121212]">{detail.campaign.slug}</p></div><div className="text-left text-sm text-[#121212] sm:text-right"><span className={`inline-flex px-2 py-1 text-xs font-semibold capitalize ${statusClass(detail.campaign.status)}`}>{detail.campaign.status}</span><p className="mt-2">{detail.campaign.trafficSourceName ?? "No traffic source"}</p></div></header>
    <section className="mt-8 grid gap-px border-x-2 border-b-2 border-[#121212] bg-[#121212] sm:grid-cols-2 xl:grid-cols-5" aria-label="Campaign metrics"><Metric label="Clicks" value={detail.metrics.clicks.toLocaleString()} /><Metric label="Conversions" value={detail.metrics.conversions.toLocaleString()} /><Metric label="Rate" value={detail.metrics.conversionRate === null ? "—" : `${(detail.metrics.conversionRate * 100).toFixed(2)}%`} /><Metric label="Revenue" value={formatMinor(detail.metrics.revenueMinor, detail.campaign.defaultCurrency)} /><Metric label="Failed delivery" value={detail.metrics.permanentlyFailedDeliveries.toLocaleString()} tone={detail.metrics.permanentlyFailedDeliveries > 0 ? "alert" : "normal"} /></section>
    <form method="get" className="mt-8 flex flex-col gap-3 border-2 border-[#121212] bg-[#FFFFFF] p-4 sm:flex-row sm:items-end"><label className="text-xs font-semibold uppercase tracking-[0.12em] text-[#121212]">From<input type="date" name="from" defaultValue={query.get("from") ?? ""} className="mt-2 block border-2 border-[#121212] bg-white px-3 py-2 text-sm" /></label><label className="text-xs font-semibold uppercase tracking-[0.12em] text-[#121212]">To<input type="date" name="to" defaultValue={query.get("to") ?? ""} className="mt-2 block border-2 border-[#121212] bg-white px-3 py-2 text-sm" /></label><label className="text-xs font-semibold uppercase tracking-[0.12em] text-[#121212]">Event<input name="eventType" defaultValue={query.get("eventType") ?? ""} placeholder="purchase" className="mt-2 block border-2 border-[#121212] bg-white px-3 py-2 text-sm" /></label><button type="submit" className="border-2 border-[#121212] bg-[#121212] px-4 py-2 text-sm font-semibold text-white hover:bg-[#D02020]">Apply range</button></form>
    <div className="mt-10 grid gap-10 xl:grid-cols-[1.1fr_0.9fr]"><section><h2 className="text-xl font-semibold">Daily trend</h2><p className="mt-1 text-sm text-[#121212]">Persisted clicks and conversions by UTC day.</p><div className="mt-4 overflow-x-auto border-2 border-[#121212] bg-[#FFFFFF]"><table className="w-full min-w-[520px] border-collapse text-left text-sm"><thead className="bg-[#E0E0E0] text-xs uppercase tracking-[0.1em] text-[#121212]"><tr><th className="px-4 py-3">Day</th><th className="px-4 py-3">Clicks</th><th className="px-4 py-3">Conversions</th><th className="px-4 py-3">Revenue</th></tr></thead><tbody>{detail.dailyMetrics.length === 0 ? <tr><td colSpan={4} className="px-4 py-8 text-sm text-[#121212]">No activity in this range.</td></tr> : detail.dailyMetrics.map((day) => <tr key={day.date} className="border-t-2 border-[#121212]"><td className="px-4 py-3">{dayFormatter.format(new Date(`${day.date}T00:00:00Z`))}</td><td className="px-4 py-3 font-mono">{day.clicks}</td><td className="px-4 py-3 font-mono">{day.conversions}</td><td className="px-4 py-3 font-mono">{formatMinor(day.revenueMinor, detail.campaign.defaultCurrency)}</td></tr>)}</tbody></table></div></section><section><h2 className="text-xl font-semibold">Delivery failures</h2><p className="mt-1 text-sm text-[#121212]">Retryable and terminal failures requiring attention.</p><div className="mt-4 border-2 border-[#121212] bg-[#FFFFFF]">{detail.deliveryFailures.length === 0 ? <p className="px-4 py-8 text-sm text-[#121212]">No delivery failures for this campaign.</p> : <ul>{detail.deliveryFailures.map((failure) => <li key={failure.id} className="border-t-2 border-[#121212] px-4 py-4 first:border-t-0"><div className="flex items-center justify-between gap-3"><span className="font-medium">{failure.conversion.eventType} <span className="font-mono text-xs text-[#121212]">{shortId(failure.conversion.eventId)}</span></span><span className={`px-2 py-1 text-xs font-semibold capitalize ${statusClass(failure.status)}`}>{failure.status.replaceAll("_", " ")}</span></div><p className="mt-2 text-xs text-[#121212]">Attempts: {failure.attemptCount} · {dateFormatter.format(failure.updatedAt)} UTC</p>{failure.lastError ? <p className="mt-2 break-words text-xs text-[#D02020]">{failure.lastError}</p> : null}</li>)}</ul>}</div></section></div>
    <div className="mt-10 grid gap-10 xl:grid-cols-2"><ActivityTable title="Recent clicks" headers={["Click ID", "Captured", "Tokens"]}>{detail.recentClicks.map((click) => <tr key={click.clickId} className="border-t-2 border-[#121212]"><td className="px-4 py-3 font-mono text-xs">{shortId(click.clickId)}</td><td className="whitespace-nowrap px-4 py-3 text-xs text-[#121212]">{dateFormatter.format(click.clickedAt)} UTC</td><td className="max-w-72 truncate px-4 py-3 text-xs text-[#121212]">{tokenSummary(click.trackingTokens)}</td></tr>)}</ActivityTable><ActivityTable title="Recent conversions" headers={["Event", "Value", "Received", "Delivery"]}>{detail.recentConversions.map((conversion) => <tr key={conversion.id} className="border-t-2 border-[#121212]"><td className="px-4 py-3"><span className="font-medium">{conversion.eventType}</span><span className="mt-1 block font-mono text-[11px] text-[#121212]">{shortId(conversion.eventId)}</span></td><td className="whitespace-nowrap px-4 py-3 font-mono text-xs">{formatMinor(Number(conversion.valueMinor), conversion.currency)}</td><td className="whitespace-nowrap px-4 py-3 text-xs text-[#121212]">{dateFormatter.format(conversion.receivedAt)} UTC</td><td className="px-4 py-3 text-xs">{conversion.outboundPostbacks.length === 0 ? "not queued" : conversion.outboundPostbacks.map((postback) => <span key={postback.status} className="mr-1 inline-flex px-2 py-1 capitalize" >{postback.status.replaceAll("_", " ")}</span>)}</td></tr>)}</ActivityTable></div>
  </div></main>;
}

function Metric({ label, value, tone = "normal" }: { label: string; value: string; tone?: "normal" | "alert" }) { return <div className="bg-[#FFFFFF] px-5 py-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#121212]">{label}</p><p className={`mt-3 text-2xl font-semibold tracking-[-0.04em] ${tone === "alert" ? "text-[#D02020]" : "text-[#121212]"}`}>{value}</p></div>; }
function tokenSummary(value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value)) return "—"; const entries = Object.entries(value); return entries.length ? entries.map(([key, token]) => `${key}=${String(token)}`).join(" · ") : "—"; }
function ActivityTable({ title, headers, children }: { title: string; headers: string[]; children: React.ReactNode }) { return <section className="min-w-0"><h2 className="text-xl font-semibold">{title}</h2><div className="mt-4 overflow-x-auto border-2 border-[#121212] bg-[#FFFFFF]"><table className="w-full min-w-[520px] border-collapse text-left text-sm"><thead className="bg-[#E0E0E0] text-xs uppercase tracking-[0.1em] text-[#121212]"><tr>{headers.map((header) => <th key={header} className="px-4 py-3">{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div></section>; }
